
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt first model"
      columns:
          - name: id
            description: "The primary key for this table"

    - name: my_second_dbt_model
      description: "A starter dbt second model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
